@startuml
'https://plantuml.com/class-diagram
'Domain Model'

class Kunde{
Mail
Telefon nummer
Adresse
}
class Sælger {
Kontaktinfo
}
class Ordre{
Status
Pris
Dato
}

class Carport {
Pris
Dimensioner
}

class Stykliste {
Materialer
}

'pile'
Kunde -- Ordre: 0-~
Ordre -- Carport: 1-~
Sælger -- Ordre: 0-~
Carport -- Stykliste: 1


@enduml