@startuml
[*] --> Index

state "index.html" as Index #Application
state "login.html" as Login #Aquamarine
state "createuser.html" as Opret #Aquamarine

Index --> Login : Trykker "log ind"
Index --> Opret : Trykker "Opret bruger"

state LoginProces {
  [*] --> IndtastInfo
  IndtastInfo --> Autentifikation : Sender indtastning
  Autentifikation --> LoginSucces : Findes i db
  Autentifikation --> LoginFejl : Findes ikke i db
  LoginFejl --> IndtastInfo : Prøv igen
  LoginSucces --> [*] : Logget ind

}

state OpretProces {
  [*] --> IndtastOplysninger
  IndtastOplysninger --> Validering : Sender indtastning
  Validering --> Succes : Opfylder krav
  Validering --> Fejl : Opfylder ikke krav
  Fejl --> IndtastOplysninger : Prøv igen
  Succes --> [*] : Oprettet i databasen
}

Login --> LoginProces
Opret --> OpretProces

@enduml