@startuml
[*] --> Index

state "index.html" as Index #Application
state "login.html" as Login #Aquamarine
state "createuser.html" as Opret #Aquamarine

Index --> Login : Trykker "log ind"
Index --> Opret : Trykker "Opret bruger"

state LoginProces {
  [*] --> Login_IndtastInfo
  Login_IndtastInfo --> Login_Autentifikation : Sender indtastning
  Login_Autentifikation --> Login_Succes : Findes i db
  Login_Autentifikation --> Login_Fejl : Findes ikke i db
  Login_Fejl --> Login_IndtastInfo : Prøv igen
  Login_Succes --> [*] : Logget ind
}

state OpretProces {
  [*] --> Opret_IndtastOplysninger
  Opret_IndtastOplysninger --> Opret_Validering : Sender indtastning
  Opret_Validering --> Opret_Succes : Opfylder krav
  Opret_Validering --> Opret_Fejl : Opfylder ikke krav
  Opret_Fejl --> Opret_IndtastOplysninger : Prøv igen
  Opret_Succes --> [*] : Oprettet i databasen
}

Login --> LoginProces
Opret --> OpretProces

@enduml
