@startuml
' Initial state
[*] --> Index

' state to allow naming and coloring
state "index.html" as Index #Application
state "login.html" as Login #Aquamarine
state "createuser.html" as Opret #Aquamarine
state "admin.html" as Admin #Coral
state "customer.html" as Customer
state "svg.html" as SVG
state "orderdetails.html" as OrderDetails #Gold

' States
Index --> Login : "Log ind"
Index --> Opret : "Opret bruger"
Index --> Admin : "Ordreoversigt"
Index --> Customer : "Fog konto"
Index --> SVG : "Generer tegning"
note left of Admin : Admin login kan tilgå
note left of Customer : Kunde login kan tilgå

Login --> Opret : "Opret bruger"
Login --> Index : "Hjem"
Opret --> Index : "Hjem"
Opret --> Login : "Log ind"

Admin --> SVG : "Se tegning"
Admin --> OrderDetails : "Se stykliste"
Admin --> Index : "Hjem"
Customer --> SVG : "Se tegning"
Customer --> OrderDetails : "Se stykliste"
Customer --> Index : "Hjem"

SVG --> Index : "Hjem"
SVG --> Customer : "Fog konto"
SVG --> Admin : "Ordreoversigt"

OrderDetails --> Admin : "Ordreoversigt"
OrderDetails --> Customer : "Fog konto"
OrderDetails --> Index : "Hjem"
note left of OrderDetails : Kunde har adgang efter betaling

@enduml
